### ISSUE TITLE
Issue using diffeditor with gatsby

### ISSUE THREAD

**Issue by bhaskarSingh** [suren-atoyan/monaco-react#62]
**Describe the bug**
Whenever I try to use DiffEditor with gatsby it throws this error: TypeError: editorRef.current.setScrollPosition is not a function

**To Reproduce**

1. install gatsby
2. Add `<DiffEditor
        height="90vh"
        language="javascript"
        original={'Hi'}
        modified={'Yo'}
        options={{
          minimap: { enabled: false },
          readOnly: true,
          fontSize: 14,
          fontFamily: 'Electrolize',
          renderSideBySide: false,
        }}
      />`
3. Run the dev server
4. See the error: Uncaught TypeError: editorRef.current.setScrollPosition is not a function

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**
![Screenshot 2020-03-15 at 7 26 13 PM](https://user-images.githubusercontent.com/16613455/76702922-a0423100-66f3-11ea-8feb-9fcddb9ce601.png)

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: [Mac iOS]
 - Browser [chrome]

**Additional context**

**Comment by suren-atoyan** [comment]
Hello @bhaskarSingh. Could you please check the new version (3.1.2)?

**Comment by bhaskarSingh** [comment]
Hey, @suren-atoyan it's working fine on version 3.1.2 
Thank you for the prompt response!
